### ISSUE TITLE
Compile error: no 'now' in 'time'

### ISSUE THREAD

**Issue by martinellison** [saschagrunert/mowl#2]
I'm getting a compile error from mowl:

```
  Compiling mowl v1.3.0
error[E0432]: unresolved import `time::now`
  --> /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/mowl-1.3.0/src/lib.rs:26:5
   |
26 | use time::now;
   |     ^^^^^^^^^ no `now` in the root
...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `mowl`
```

For time I am getting `time v0.2.25`, according to `cargo tree`. This is the latest version according to `https://github.com/time-rs/time`. According to [the doco for 0.2.25](https://docs.rs/time/0.2.25/time/struct.Time.html#method.now), this *deprecates* `now()`.

Maybe you could use `std::time::SystemTime::now()`, `std::time::Instant::now()`, or the `chrono` crate's `Local::now()` or `Utc::now()`.

**Comment by saschagrunert** [comment]
Hey @martinellison, yeah this makes sense, do you wanna work on that and propose a PR? :)

**Comment by martinellison** [comment]
ok, created a PR. Time/date format may be wrong, and note that it is UTC (I think as before).

**Comment by saschagrunert** [comment]
Thank you for the fix, I'll cut a new release in the next days. :+1:
